/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ocean.confluent.schemaregistry.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2042991238600659815L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserDto\",\"namespace\":\"com.ocean.confluent.schemaregistry.avro.dto\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"the first name of a person\"},{\"name\":\"age\",\"type\":\"int\",\"doc\":\"the last name of a person\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserDto> ENCODER =
      new BinaryMessageEncoder<UserDto>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserDto> DECODER =
      new BinaryMessageDecoder<UserDto>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserDto>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** the first name of a person */
   private java.lang.CharSequence name;
  /** the last name of a person */
   private int age;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserDto() {}

  /**
   * All-args constructor.
   * @param name the first name of a person
   * @param age the last name of a person
   */
  public UserDto(java.lang.CharSequence name, java.lang.Integer age) {
    this.name = name;
    this.age = age;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return age;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: age = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return the first name of a person
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * the first name of a person
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return the last name of a person
   */
  public int getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * the last name of a person
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.age = value;
  }

  /**
   * Creates a new UserDto RecordBuilder.
   * @return A new UserDto RecordBuilder
   */
  public static com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder newBuilder() {
    return new com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder();
  }

  /**
   * Creates a new UserDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserDto RecordBuilder
   */
  public static com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder newBuilder(com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder other) {
    if (other == null) {
      return new com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder();
    } else {
      return new com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder(other);
    }
  }

  /**
   * Creates a new UserDto RecordBuilder by copying an existing UserDto instance.
   * @param other The existing instance to copy.
   * @return A new UserDto RecordBuilder
   */
  public static com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder newBuilder(com.ocean.confluent.schemaregistry.avro.dto.UserDto other) {
    if (other == null) {
      return new com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder();
    } else {
      return new com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserDto>
    implements org.apache.avro.data.RecordBuilder<UserDto> {

    /** the first name of a person */
    private java.lang.CharSequence name;
    /** the last name of a person */
    private int age;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UserDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ocean.confluent.schemaregistry.avro.dto.UserDto other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * the first name of a person
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * the first name of a person
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * the first name of a person
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * the first name of a person
      * @return This builder.
      */
    public com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * the last name of a person
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * the last name of a person
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder setAge(int value) {
      validate(fields()[1], value);
      this.age = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * the last name of a person
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'age' field.
      * the last name of a person
      * @return This builder.
      */
    public com.ocean.confluent.schemaregistry.avro.dto.UserDto.Builder clearAge() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserDto build() {
      try {
        UserDto record = new UserDto();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.age = fieldSetFlags()[1] ? this.age : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserDto>
    READER$ = (org.apache.avro.io.DatumReader<UserDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeInt(this.age);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.age = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.age = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










